IF (NOT EXISTS (SELECT *  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo'  
	AND TABLE_NAME = 'JobPost'  AND COLUMN_NAME='IsDisabled' AND DATA_TYPE = 'BIT'))
BEGIN
	ALTER TABLE [dbo].[JobPost] ADD [IsDisabled] BIT NOT NULL DEFAULT 0
END;
IF (NOT EXISTS (SELECT *  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo'  
	AND TABLE_NAME = 'JobPost'  AND COLUMN_NAME='Note'))
BEGIN
	ALTER TABLE [dbo].[JobPost] ADD [Note] NVARCHAR(MAX) NULL DEFAULT ''
END;