IF (NOT EXISTS (SELECT *  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo'  
	AND TABLE_NAME = 'Question'  AND COLUMN_NAME='IsDisabled' AND DATA_TYPE = 'BIT'))
BEGIN
	ALTER TABLE [dbo].[Question] ADD [IsDisabled] BIT NOT NULL DEFAULT 0
END;