#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH.CodeGen.Templates.Code
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class EntityService : EntityServiceBase
{

#line hidden

#line 1 "EntityService.cshtml"
public BH.CodeGen.Model.Settings Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("using BH.Models;\nusing BH.Models.ViewModels;\nusing BH.Repositories;\nusing BH.Repo" +
"sitories.Interface;\nusing BH.Services.Interface;\nusing Microsoft.Extensions.Logg" +
"ing;\n\nnamespace BH.Services\n{\n    public class ");


#line 11 "EntityService.cshtml"
            Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral(" : I");


#line 11 "EntityService.cshtml"
                                   Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral("\n    {\n        private readonly ILogger<");


#line 13 "EntityService.cshtml"
                             Write(Model.RepoName);


#line default
#line hidden
WriteLiteral("> _logger;\n        private readonly I");


#line 14 "EntityService.cshtml"
                      Write(Model.RepoName);


#line default
#line hidden
WriteLiteral(" _repo;\n        public ");


#line 15 "EntityService.cshtml"
           Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral("(ILogger<");


#line 15 "EntityService.cshtml"
                                        Write(Model.RepoName);


#line default
#line hidden
WriteLiteral("> logger, I");


#line 15 "EntityService.cshtml"
                                                                    Write(Model.RepoName);


#line default
#line hidden
WriteLiteral(" repo)\n        {\n            _logger = logger;\n            _repo = repo;\n        " +
"}\n\n        public async Task<ResultModel<");


#line 21 "EntityService.cshtml"
                                  Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("Model>> Save");


#line 21 "EntityService.cshtml"
                                                                Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("(");


#line 21 "EntityService.cshtml"
                                                                                   Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("RequestModel model)\n        {\n            _logger.LogInformation(\"Going to execut" +
"e Method: Save");


#line 23 "EntityService.cshtml"
                                                             Write(Model.ClassName);


#line default
#line hidden
WriteLiteral(", Class: ");


#line 23 "EntityService.cshtml"
                                                                                       Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral("\");\n            var result = await _repo.Save");


#line 24 "EntityService.cshtml"
                                     Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("(model);\n            _logger.LogInformation(\"Execution completed Method: Save");


#line 25 "EntityService.cshtml"
                                                                Write(Model.ClassName);


#line default
#line hidden
WriteLiteral(", Class: ");


#line 25 "EntityService.cshtml"
                                                                                          Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral("\");\n            return await Get");


#line 26 "EntityService.cshtml"
                        Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("ById(result);\n        }\n\n        public async Task<ResultModel<");


#line 29 "EntityService.cshtml"
                                  Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("Model>> Get");


#line 29 "EntityService.cshtml"
                                                               Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("ById(int id)\n        {\n            _logger.LogInformation(\"Going to execute Metho" +
"d: Get");


#line 31 "EntityService.cshtml"
                                                            Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("ById, Class: ");


#line 31 "EntityService.cshtml"
                                                                                          Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral("\");\n            var result = await _repo.Get");


#line 32 "EntityService.cshtml"
                                    Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("ById(id);\n            _logger.LogInformation(\"Execution completed Method: Get");


#line 33 "EntityService.cshtml"
                                                               Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("ById, Class: ");


#line 33 "EntityService.cshtml"
                                                                                             Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral("\");\n            return result;\n        }\n\n        public async Task<ResultModel<L" +
"ist<");


#line 37 "EntityService.cshtml"
                                       Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("Model>>> GetAll");


#line 37 "EntityService.cshtml"
                                                                        Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("(");


#line 37 "EntityService.cshtml"
                                                                                           Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("ListModel model)\n        {\n            _logger.LogInformation(\"Going to execute M" +
"ethod: GetAll");


#line 39 "EntityService.cshtml"
                                                               Write(Model.ClassName);


#line default
#line hidden
WriteLiteral(", Class: ");


#line 39 "EntityService.cshtml"
                                                                                         Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral("\");\n            var result = await _repo.GetAll");


#line 40 "EntityService.cshtml"
                                       Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("(model);\n            _logger.LogInformation(\"Execution completed Method: GetAll");


#line 41 "EntityService.cshtml"
                                                                  Write(Model.ClassName);


#line default
#line hidden
WriteLiteral(", Class: ");


#line 41 "EntityService.cshtml"
                                                                                            Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral("\");\n            return result;\n        }\n\n        public async Task<ResultModel<i" +
"nt>> GetAll");


#line 45 "EntityService.cshtml"
                                              Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("Count(");


#line 45 "EntityService.cshtml"
                                                                      Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("ListModel model)\n        {\n            _logger.LogInformation(\"Going to execute M" +
"ethod: GetAll");


#line 47 "EntityService.cshtml"
                                                               Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("Count, Class: ");


#line 47 "EntityService.cshtml"
                                                                                              Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral("\");\n            var result = await _repo.GetAll");


#line 48 "EntityService.cshtml"
                                       Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("Count(model);\n            _logger.LogInformation(\"Execution completed Method: Get" +
"All");


#line 49 "EntityService.cshtml"
                                                                  Write(Model.ClassName);


#line default
#line hidden
WriteLiteral("Count, Class: ");


#line 49 "EntityService.cshtml"
                                                                                                 Write(Model.ServiceName);


#line default
#line hidden
WriteLiteral("\");\n            return result;\n        }\n    }\n}\n\n\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class EntityServiceBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
